image: node:latest

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
    - npm install dotenv

test:
  stage: test
  script:
    - npm run test
