image: node:buster

services:
  - mongo:latest

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - apt-get update -qq && apt-get install -y libssl1.1
    - cd /builds/c21054715/energy_visualization_team2/Code
    - npm install
    - npm install dotenv
    - npm install --save-dev jest

test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y libssl1.1
    - cd /builds/c21054715/energy_visualization_team2/Code/Backend
    - jest --clearCache
    - npm install
    - npm install dotenv
    - npm install --save-dev jest
    - npm install to-fast-properties
    - set NODE_OPTIONS=--max_old_space_size=4096
    - npm run test
    - cd /builds/c21054715/energy_visualization_team2/Code/Frontend
    - npm install
    - npm install dotenv
    - npm install --save-dev jest
    - npm install identity-obj-proxy --save-dev
    - npm install to-fast-properties
    - npm run test
